repos:
  - repo: local
    hooks:
      - id: install
        name: install
        entry: npm install
        files: ".*(vue|ts)"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npm run lint
        files: ".*(vue|ts)"
        language: system
        pass_filenames: false
